[workspace]
resolver = "2"
members = [
    "crates/zeroterm-core",
    "crates/zeroterm-render",
    "crates/zeroterm-mux",
    "crates/zeroterm-config",
    "crates/zeroterm-sync",
    "crates/zeroterm-ssh",
    "crates/zeroterm-plugin",
    "crates/zeroterm",
]

[workspace.dependencies]
tokio = { version = "1.38", features = ["full", "rt-multi-thread", "macros", "tracing"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "json", "env-filter"] }
pollster = "0.4"
anyhow = "1.0"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
mlua = { version = "0.12", features = ["serde", "send", "async", "lua54", "vendored"] }
winit = "0.30"
wgpu = "23"
portable-pty = "0.8"
swash = "0.2"
unicode-width = "0.1"
unicode-segmentation = "1.7"
chacha20poly1305 = "0.10"
chacha20 = "0.9"
poly1305 = "0.9"
zeroize = "1.8"
reqwest = { version = "0.12", features = ["json", "rustls-tls"] }
criterion = "0.5"
dirs = "5.0"
wasmtime = "28"
wasmtime-wasi = { version = "28", features = ["preview1"] }
wat = "1"
image = { version = "0.25", default-features = false, features = ["png", "gif", "webp"] }

[workspace.package]
version = "0.3.6"
edition = "2021"
license = "MIT"

[profile.dev]
opt-level = 1
debug = true

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"
debug = false

[profile.bench]
opt-level = 3
debug = true