//! Detached-session ("daemon mode") support.
//!
//! The requirement: a remote long-running shell must survive the local client
//! disconnecting, and a later client must be able to re-attach. Reimplementing
//! a pty-spawning daemon is out of scope, so the remote work is delegated to an
//! already-present remote agent: `tmux` (fallbacks: `screen`, `dtach`).
//!
//! Protocol: [`daemon_start`] (on `SshSession`) execs `tmux new-session -d -s
//! <id> <command>` on the remote host, which detaches the session so it outlives
//! this SSH channel; the generated command echoes a [`SESSION_ID_MARKER`] line
//! recoverable by [`parse_session_id`]. [`daemon_attach`] re-establishes it via
//! `tmux attach-session -t <id>`. The [`SessionRegistry`] is purely local
//! metadata about which detached sessions this client started.
//!
//! ponytail: only `tmux` is generated by the protocol functions. `screen` and
//! `dtach` are candidates, not generated — probing the remote host for whichever
//! agent exists is the upgrade path if tmux is not ubiquitous enough.
//!
//! All functions in this module are pure (no I/O), so the whole registry and
//! re-attach protocol unit-tests without a network or an SSH connection.

use std::collections::HashMap;

/// Max sessions kept in a [`SessionRegistry`]. Oldest entries are evicted on
/// overflow.
///
/// ponytail: fixed cap with a linear oldest-scan on overflow; no LRU structure —
/// fine until a registry holds thousands of sessions.
const MAX_SESSIONS: usize = 64;

/// Marker echoed by the remote detached-start command so a client can recover
/// the session id from the terminal stream.
pub const SESSION_ID_MARKER: &str = "ZEROTERM_SESSION=";

/// Metadata for one detached remote session. Serializable so a client could
/// persist the registry across restarts.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct DetachedSession {
    pub id: String,
    pub host: String,
    /// Unix timestamp, nanoseconds since the epoch.
    pub start_ts: u64,
    pub command: String,
}

/// In-memory registry of detached sessions started by this client.
#[derive(Debug, Clone, Default)]
pub struct SessionRegistry {
    map: HashMap<String, DetachedSession>,
}

impl SessionRegistry {
    pub fn new() -> Self {
        Self::default()
    }

    /// Insert (or overwrite) a session, evicting the oldest entry when at
    /// capacity. Returns the stored entry.
    pub fn create(&mut self, id: String, host: String, command: String) -> &DetachedSession {
        let start_ts = unix_now();
        if !self.map.contains_key(&id) && self.map.len() >= MAX_SESSIONS {
            if let Some(oldest) = self
                .map
                .iter()
                .min_by_key(|(_, s)| s.start_ts)
                .map(|(k, _)| k.clone())
            {
                self.map.remove(&oldest);
            }
        }
        let entry = DetachedSession {
            id: id.clone(),
            host,
            start_ts,
            command,
        };
        self.map.insert(id.clone(), entry);
        self.map.get(&id).expect("just inserted")
    }

    pub fn get(&self, id: &str) -> Option<&DetachedSession> {
        self.map.get(id)
    }

    pub fn has(&self, id: &str) -> bool {
        self.map.contains_key(id)
    }

    pub fn remove(&mut self, id: &str) -> Option<DetachedSession> {
        self.map.remove(id)
    }

    /// All sessions, oldest first.
    pub fn list(&self) -> Vec<DetachedSession> {
        let mut v: Vec<DetachedSession> = self.map.values().cloned().collect();
        v.sort_by_key(|s| s.start_ts);
        v
    }
}

pub(crate) fn unix_now() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_nanos() as u64)
        .unwrap_or(0)
}

/// Re-attach command a disconnected local client runs: ssh into `host` and
/// attach the remote tmux session `id`.
pub fn encode_attach_cmd(host: &str, id: &str) -> String {
    format!("ssh {host} -t tmux attach-session -t {id}")
}

/// Extract the session id from a terminal line carrying the echoed
/// [`SESSION_ID_MARKER`] (e.g. `echo ZEROTERM_SESSION=zt-123`). Returns `None`
/// when the marker is absent or followed by nothing.
pub fn parse_session_id(line: &str) -> Option<String> {
    let idx = line.find(SESSION_ID_MARKER)?;
    let rest = &line[idx + SESSION_ID_MARKER.len()..];
    let id: String = rest.chars().take_while(|c| !c.is_whitespace()).collect();
    (!id.is_empty()).then_some(id)
}

/// Remote command that starts `command` in a new detached tmux session and
/// echoes the [`SESSION_ID_MARKER`] so a client can recover the id.
///
/// ponytail: `command` is appended raw (tmux joins trailing args), so shell
/// metacharacters in it run as-is — wrap it in `sh -c '...'` for complex
/// commands. The marker echo is single-quoted, so a command containing a
/// literal `'` would break it.
#[cfg(unix)]
pub(crate) fn detached_start_cmd(id: &str, command: &str) -> String {
    format!("tmux new-session -d -s {id} {command} && printf '{SESSION_ID_MARKER}{id}\\n'")
}

/// Remote command that re-attaches to the detached tmux session `id`.
#[cfg(unix)]
pub(crate) fn remote_attach_cmd(id: &str) -> String {
    format!("tmux attach-session -t {id}")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn registry_create_get_remove_has() {
        let mut r = SessionRegistry::new();
        assert!(!r.has("s1"));
        let s = r.create("s1".into(), "host.example".into(), "htop".into());
        assert_eq!(s.id, "s1");
        assert_eq!(s.host, "host.example");
        assert_eq!(s.command, "htop");
        assert!(r.has("s1"));
        assert_eq!(r.get("s1").map(|s| s.command.as_str()), Some("htop"));
        assert_eq!(r.get("nope"), None);

        let removed = r.remove("s1");
        assert!(removed.is_some());
        assert!(!r.has("s1"));
        assert_eq!(r.remove("s1"), None);
    }

    #[test]
    fn registry_create_overwrites_existing_id() {
        let mut r = SessionRegistry::new();
        r.create("s".into(), "h1".into(), "c1".into());
        r.create("s".into(), "h2".into(), "c2".into());
        assert_eq!(r.list().len(), 1);
        assert_eq!(r.get("s").map(|s| s.host.as_str()), Some("h2"));
    }

    #[test]
    fn registry_list_sorted_oldest_first() {
        let mut r = SessionRegistry::new();
        r.create("a".into(), "h".into(), "c".into());
        r.create("b".into(), "h".into(), "c".into());
        r.create("c".into(), "h".into(), "c".into());
        let sessions = r.list();
        let ids: Vec<&str> = sessions.iter().map(|s| s.id.as_str()).collect();
        assert_eq!(ids, vec!["a", "b", "c"]);
    }

    #[test]
    fn registry_capacity_evicts_oldest() {
        let mut r = SessionRegistry::new();
        for i in 0..MAX_SESSIONS + 1 {
            r.create(format!("id{i}"), "h".into(), "cmd".into());
        }
        assert_eq!(r.list().len(), MAX_SESSIONS);
        assert!(!r.has("id0"), "oldest should be evicted");
        assert!(r.has("id64"));
    }

    #[test]
    fn encode_attach_cmd_contains_id_and_attach() {
        let cmd = encode_attach_cmd("myhost", "zt-42");
        assert!(cmd.contains("myhost"));
        assert!(cmd.contains("zt-42"));
        assert!(cmd.contains("tmux attach-session"));
    }

    #[test]
    fn parse_session_id_roundtrip() {
        let id = "zt-123";
        assert_eq!(
            parse_session_id(&format!("{SESSION_ID_MARKER}{id}\n")),
            Some(id.to_string())
        );
        assert_eq!(
            parse_session_id(&format!("echo {SESSION_ID_MARKER}{id}")),
            Some(id.to_string())
        );
    }

    #[test]
    fn parse_session_id_garbage_is_none() {
        assert_eq!(parse_session_id(""), None);
        assert_eq!(parse_session_id("hello world"), None);
        assert_eq!(parse_session_id("ZEROTERM_SESSION="), None);
        assert_eq!(parse_session_id("ZEROTERM_SESSION=  \n"), None);
    }

    #[cfg(unix)]
    #[test]
    fn detached_start_cmd_has_id_and_marker() {
        let cmd = detached_start_cmd("zt-9", "htop");
        assert!(cmd.starts_with("tmux new-session -d -s zt-9"));
        assert!(cmd.contains(SESSION_ID_MARKER));
        assert!(cmd.contains("htop"));
    }

    #[cfg(unix)]
    #[test]
    fn remote_attach_cmd_has_id() {
        assert_eq!(remote_attach_cmd("zt-9"), "tmux attach-session -t zt-9");
    }

    #[test]
    fn detached_session_is_serializable() {
        let s = DetachedSession {
            id: "zt-1".into(),
            host: "h".into(),
            start_ts: 42,
            command: "top".into(),
        };
        let json = serde_json::to_string(&s).unwrap();
        let back: DetachedSession = serde_json::from_str(&json).unwrap();
        assert_eq!(s, back);
    }
}
