format = """
$username$hostname$directory$git_branch$git_status$cmd_duration
$character"""

[character]
success_symbol = "[❯](bold #7aa2f7)"
error_symbol = "[❯](bold #f7768e)"
vimcmd_symbol = "[❮](bold #9ece6a)"

[directory]
style = "bold #7aa2f7"
truncation_length = 3
truncate_to_repo = true

[git_branch]
symbol = " "
style = "#bb9af7"

[git_status]
style = "#e0af68"

[cmd_duration]
min_time = 500
format = "[$duration]($style) "
style = "#e0af68"

[line_break]
disabled = false

[battery]
disabled = true
